spring:



  logging:
    level:
      org:
        hibernate:
          SQL: debug
          type:
            descriptor:
              sql:
                BasicBinder: trace

  h2:
    console:
      enabled: true
      path: /h2-console